/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthIndexRouteImport } from './routes/auth.index'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthStudentRouteImport } from './routes/auth.student'
import { Route as AuthOpettajaRouteImport } from './routes/auth.opettaja'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthenticatedOpettajaRouteImport } from './routes/_authenticated/opettaja'
import { Route as AuthenticatedLiityYhteisoonRouteImport } from './routes/_authenticated/liity-yhteisoon'
import { Route as AuthenticatedSeikkailuRouteRouteImport } from './routes/_authenticated/seikkailu/route'
import { Route as AuthenticatedSeikkailuIndexRouteImport } from './routes/_authenticated/seikkailu/index'
import { Route as AuthenticatedSeikkailuScreenRouteImport } from './routes/_authenticated/seikkailu/$screen'
import { Route as AuthenticatedOpettajaOppilasUserIdRouteImport } from './routes/_authenticated/opettaja.oppilas.$userId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthStudentRoute = AuthStudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOpettajaRoute = AuthOpettajaRouteImport.update({
  id: '/opettaja',
  path: '/opettaja',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedOpettajaRoute = AuthenticatedOpettajaRouteImport.update({
  id: '/opettaja',
  path: '/opettaja',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLiityYhteisoonRoute =
  AuthenticatedLiityYhteisoonRouteImport.update({
    id: '/liity-yhteisoon',
    path: '/liity-yhteisoon',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSeikkailuRouteRoute =
  AuthenticatedSeikkailuRouteRouteImport.update({
    id: '/seikkailu',
    path: '/seikkailu',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSeikkailuIndexRoute =
  AuthenticatedSeikkailuIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSeikkailuRouteRoute,
  } as any)
const AuthenticatedSeikkailuScreenRoute =
  AuthenticatedSeikkailuScreenRouteImport.update({
    id: '/$screen',
    path: '/$screen',
    getParentRoute: () => AuthenticatedSeikkailuRouteRoute,
  } as any)
const AuthenticatedOpettajaOppilasUserIdRoute =
  AuthenticatedOpettajaOppilasUserIdRouteImport.update({
    id: '/oppilas/$userId',
    path: '/oppilas/$userId',
    getParentRoute: () => AuthenticatedOpettajaRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/seikkailu': typeof AuthenticatedSeikkailuRouteRouteWithChildren
  '/liity-yhteisoon': typeof AuthenticatedLiityYhteisoonRoute
  '/opettaja': typeof AuthenticatedOpettajaRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/opettaja': typeof AuthOpettajaRoute
  '/auth/student': typeof AuthStudentRoute
  '/auth/': typeof AuthIndexRoute
  '/seikkailu/$screen': typeof AuthenticatedSeikkailuScreenRoute
  '/seikkailu/': typeof AuthenticatedSeikkailuIndexRoute
  '/opettaja/oppilas/$userId': typeof AuthenticatedOpettajaOppilasUserIdRoute
}
export interface FileRoutesByTo {
  '/liity-yhteisoon': typeof AuthenticatedLiityYhteisoonRoute
  '/opettaja': typeof AuthenticatedOpettajaRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/opettaja': typeof AuthOpettajaRoute
  '/auth/student': typeof AuthStudentRoute
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthIndexRoute
  '/seikkailu/$screen': typeof AuthenticatedSeikkailuScreenRoute
  '/seikkailu': typeof AuthenticatedSeikkailuIndexRoute
  '/opettaja/oppilas/$userId': typeof AuthenticatedOpettajaOppilasUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/_authenticated/seikkailu': typeof AuthenticatedSeikkailuRouteRouteWithChildren
  '/_authenticated/liity-yhteisoon': typeof AuthenticatedLiityYhteisoonRoute
  '/_authenticated/opettaja': typeof AuthenticatedOpettajaRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/opettaja': typeof AuthOpettajaRoute
  '/auth/student': typeof AuthStudentRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/_authenticated/seikkailu/$screen': typeof AuthenticatedSeikkailuScreenRoute
  '/_authenticated/seikkailu/': typeof AuthenticatedSeikkailuIndexRoute
  '/_authenticated/opettaja/oppilas/$userId': typeof AuthenticatedOpettajaOppilasUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/seikkailu'
    | '/liity-yhteisoon'
    | '/opettaja'
    | '/auth/login'
    | '/auth/opettaja'
    | '/auth/student'
    | '/auth/'
    | '/seikkailu/$screen'
    | '/seikkailu/'
    | '/opettaja/oppilas/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/liity-yhteisoon'
    | '/opettaja'
    | '/auth/login'
    | '/auth/opettaja'
    | '/auth/student'
    | '/'
    | '/auth'
    | '/seikkailu/$screen'
    | '/seikkailu'
    | '/opettaja/oppilas/$userId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/seikkailu'
    | '/_authenticated/liity-yhteisoon'
    | '/_authenticated/opettaja'
    | '/auth/login'
    | '/auth/opettaja'
    | '/auth/student'
    | '/_authenticated/'
    | '/auth/'
    | '/_authenticated/seikkailu/$screen'
    | '/_authenticated/seikkailu/'
    | '/_authenticated/opettaja/oppilas/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/student': {
      id: '/auth/student'
      path: '/student'
      fullPath: '/auth/student'
      preLoaderRoute: typeof AuthStudentRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/opettaja': {
      id: '/auth/opettaja'
      path: '/opettaja'
      fullPath: '/auth/opettaja'
      preLoaderRoute: typeof AuthOpettajaRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/opettaja': {
      id: '/_authenticated/opettaja'
      path: '/opettaja'
      fullPath: '/opettaja'
      preLoaderRoute: typeof AuthenticatedOpettajaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/liity-yhteisoon': {
      id: '/_authenticated/liity-yhteisoon'
      path: '/liity-yhteisoon'
      fullPath: '/liity-yhteisoon'
      preLoaderRoute: typeof AuthenticatedLiityYhteisoonRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/seikkailu': {
      id: '/_authenticated/seikkailu'
      path: '/seikkailu'
      fullPath: '/seikkailu'
      preLoaderRoute: typeof AuthenticatedSeikkailuRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/seikkailu/': {
      id: '/_authenticated/seikkailu/'
      path: '/'
      fullPath: '/seikkailu/'
      preLoaderRoute: typeof AuthenticatedSeikkailuIndexRouteImport
      parentRoute: typeof AuthenticatedSeikkailuRouteRoute
    }
    '/_authenticated/seikkailu/$screen': {
      id: '/_authenticated/seikkailu/$screen'
      path: '/$screen'
      fullPath: '/seikkailu/$screen'
      preLoaderRoute: typeof AuthenticatedSeikkailuScreenRouteImport
      parentRoute: typeof AuthenticatedSeikkailuRouteRoute
    }
    '/_authenticated/opettaja/oppilas/$userId': {
      id: '/_authenticated/opettaja/oppilas/$userId'
      path: '/oppilas/$userId'
      fullPath: '/opettaja/oppilas/$userId'
      preLoaderRoute: typeof AuthenticatedOpettajaOppilasUserIdRouteImport
      parentRoute: typeof AuthenticatedOpettajaRoute
    }
  }
}

interface AuthenticatedSeikkailuRouteRouteChildren {
  AuthenticatedSeikkailuScreenRoute: typeof AuthenticatedSeikkailuScreenRoute
  AuthenticatedSeikkailuIndexRoute: typeof AuthenticatedSeikkailuIndexRoute
}

const AuthenticatedSeikkailuRouteRouteChildren: AuthenticatedSeikkailuRouteRouteChildren =
  {
    AuthenticatedSeikkailuScreenRoute: AuthenticatedSeikkailuScreenRoute,
    AuthenticatedSeikkailuIndexRoute: AuthenticatedSeikkailuIndexRoute,
  }

const AuthenticatedSeikkailuRouteRouteWithChildren =
  AuthenticatedSeikkailuRouteRoute._addFileChildren(
    AuthenticatedSeikkailuRouteRouteChildren,
  )

interface AuthenticatedOpettajaRouteChildren {
  AuthenticatedOpettajaOppilasUserIdRoute: typeof AuthenticatedOpettajaOppilasUserIdRoute
}

const AuthenticatedOpettajaRouteChildren: AuthenticatedOpettajaRouteChildren = {
  AuthenticatedOpettajaOppilasUserIdRoute:
    AuthenticatedOpettajaOppilasUserIdRoute,
}

const AuthenticatedOpettajaRouteWithChildren =
  AuthenticatedOpettajaRoute._addFileChildren(
    AuthenticatedOpettajaRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSeikkailuRouteRoute: typeof AuthenticatedSeikkailuRouteRouteWithChildren
  AuthenticatedLiityYhteisoonRoute: typeof AuthenticatedLiityYhteisoonRoute
  AuthenticatedOpettajaRoute: typeof AuthenticatedOpettajaRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSeikkailuRouteRoute:
    AuthenticatedSeikkailuRouteRouteWithChildren,
  AuthenticatedLiityYhteisoonRoute: AuthenticatedLiityYhteisoonRoute,
  AuthenticatedOpettajaRoute: AuthenticatedOpettajaRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthOpettajaRoute: typeof AuthOpettajaRoute
  AuthStudentRoute: typeof AuthStudentRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthOpettajaRoute: AuthOpettajaRoute,
  AuthStudentRoute: AuthStudentRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
